name: Update Dependencies
on:
  workflow_dispatch:
  schedule:
    - cron: '00 6 1 * *'
jobs:
  update-dependencies:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Perform dependencies resolution and update
        run: ./gradlew versionCatalogUpdate
      - name: Get current date
        run: echo "today=$(date +'%Y-%m-%d')" >> $GITHUB_ENV
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: update dependencies
          committer: GitHub <noreply@github.com>
          author: GitHub <noreply@github.com>
          title: Update dependencies
          body: |
              Dependencies update.
              Check the Version Catalog to see which dependencies need an update.

          branch: update-dependencies-${{ env.today }}
          delete-branch: true
          labels: |
            dependencies update
            auto pr
          reviewers: |
            antunflas
            giorgioprovenzale
            BraneRi
            JonatanPlesko
            schalke95

